const I=(n,p,img,t=false,s=false)=>({n,p,img,t,s});
const S={
 cafe:{title:'카페',desc:'커피 · 스무디 · 차 · 에이드 · 디저트',hero:'assets-final/cafe_americano.webp',cats:{
  '커피':[I('아메리카노',4000,'assets-final/cafe_americano.webp',1,1),I('카페라떼',4500,'assets-final/cafe_cafelatte.webp',1,1),I('바닐라라떼',5000,'assets-final/cafe_vanillalatte.webp',1,1),I('카라멜마키아토',5200,'assets-final/cafe_caramelmacchiato.webp',1,1),I('카페모카',5000,'assets-final/cafe_cafemocha.webp',1,1),I('아인슈페너',5500,'assets-final/cafe_einspanner.webp',0,1)],
  '스무디':[I('딸기스무디',5500,'assets-final/cafe_strawberrysmoothie.webp',0,1),I('망고스무디',5500,'assets-final/cafe_mangosmoothie.webp',0,1),I('블루베리스무디',5800,'assets-final/cafe_blueberrysmoothie.webp',0,1),I('요거트스무디',5200,'assets-final/cafe_yogurtsmoothie.webp',0,1)],
  '차':[I('레몬차',4200,'assets-final/cafe_lemontea.webp',1,1),I('자몽차',4500,'assets-final/cafe_grapefruittea.webp',1,1),I('녹차라떼',4500,'assets-final/cafe_greentealatte.webp',1,1),I('초코라떼',4500,'assets-final/cafe_chocolatelatte.webp',1,1)],
  '에이드':[I('레몬에이드',4800,'assets-final/cafe_lemonade.webp',0,1),I('자몽에이드',5000,'assets-final/cafe_grapefruittea.webp',0,1)],
  '디저트':[I('소프트아이스크림',1800,'assets-final/burger_softicecream.webp')]
 }},
 burger:{title:'햄버거 가게',desc:'버거 · 세트 · 사이드 · 치킨 · 음료 · 디저트',hero:'assets-final/burger_bulgogiburger.webp',cats:{
  '버거':[I('불고기버거',4800,'assets-final/burger_bulgogiburger.webp'),I('치즈버거',5000,'assets-final/burger_cheeseburger.webp'),I('더블치즈버거',6500,'assets-final/burger_doublecheeseburger.webp'),I('베이컨버거',6200,'assets-final/burger_baconburger.webp'),I('치킨버거',5500,'assets-final/burger_chickenburger.webp'),I('새우버거',5600,'assets-final/burger_shrimpburger.webp')],
  '세트':[I('불고기버거 세트',7800,'assets-final/burger_bulgogiset.webp'),I('치즈버거 세트',8000,'assets-final/burger_cheeseburgerset.webp')],
  '사이드':[I('감자튀김',2500,'assets-final/burger_frenchfries.webp',0,1),I('어니언링',3000,'assets-final/burger_onionrings.webp'),I('치즈스틱',2800,'assets-final/burger_cheesesticks.webp')],
  '치킨':[I('치킨너겟',3200,'assets-final/burger_chickennuggets.webp')],
  '음료':[I('콜라',2200,'assets-final/burger_cola.webp',0,1),I('사이다',2200,'assets-final/burger_cider.webp',0,1)],
  '디저트':[I('소프트아이스크림',1800,'assets-final/burger_softicecream.webp')]
 }},
 bunsik:{title:'분식집',desc:'떡볶이 · 김밥 · 튀김 · 면 · 식사 · 음료',hero:'assets-final/bunsik_tteokbokki.webp',cats:{
  '떡볶이':[I('떡볶이',4000,'assets-final/bunsik_tteokbokki.webp'),I('치즈떡볶이',5000,'assets-final/bunsik_cheesetteokbokki.webp'),I('로제떡볶이',5500,'assets-final/bunsik_rosetteokbokki.webp'),I('라볶이',5000,'assets-final/bunsik_rabokki.webp')],
  '김밥':[I('김밥',3000,'assets-final/bunsik_gimbap.webp'),I('참치김밥',4000,'assets-final/bunsik_tunagimbap.webp'),I('치즈김밥',3800,'assets-final/bunsik_cheesegimbap.webp'),I('돈가스김밥',4500,'assets-final/bunsik_porkcutletgimbap.webp')],
  '튀김':[I('모둠튀김',4500,'assets-final/bunsik_assortedtempura.webp'),I('김말이',3000,'assets-final/bunsik_gimmari.webp'),I('오징어튀김',3500,'assets-final/bunsik_squidtempura.webp'),I('야채튀김',3000,'assets-final/bunsik_vegetabletempura.webp')],
  '면':[I('라면',4000,'assets-final/bunsik_ramen.webp'),I('쫄면',5000,'assets-final/bunsik_jjolmyeon.webp'),I('우동',5000,'assets-final/bunsik_udon.webp')],
  '식사':[I('김밥',3000,'assets-final/bunsik_gimbap.webp'),I('라볶이',5000,'assets-final/bunsik_rabokki.webp')],
  '음료':[I('콜라',2000,'assets-final/burger_cola.webp',0,1),I('사이다',2000,'assets-final/burger_cider.webp',0,1)]
 }}
};
let store=null,cat=null,mode='free',orderType='매장',cart=[],mission=null,money=0;const $=x=>document.getElementById(x),won=n=>n.toLocaleString('ko-KR')+'원';
function home(){$('stores').innerHTML=Object.entries(S).map(([k,v])=>`<button class="store-card" onclick="enter('${k}')"><img src="${v.hero}" alt="${v.title}"><div class="store-body"><div class="store-name">${v.title}</div><div class="store-desc">${v.desc}</div><span class="store-go">주문하기</span></div></button>`).join('')}
function enter(k){store=k;cat=Object.keys(S[k].cats)[0];cart=[];document.body.className=k;$('home').classList.add('hidden');$('app').classList.remove('hidden');$('brand').textContent=S[k].title+' 키오스크';setMode('free');setOrderType('매장');renderCats();renderMenu();renderCart();scrollTo(0,0)}
function goHome(){$('app').classList.add('hidden');$('home').classList.remove('hidden');document.body.className='';closeModal();scrollTo(0,0)}
function setMode(m){mode=m;$('freeBtn').classList.toggle('on',m==='free');$('missionBtn').classList.toggle('on',m==='mission');$('missionBox').classList.toggle('hidden',m!=='mission');$('modeText').textContent=m==='free'?'자유롭게 주문해 보세요.':'미션을 보고 정확하게 주문해 보세요.';if(m==='mission')newMission()}
function setOrderType(t){orderType=t;$('dine').classList.toggle('on',t==='매장');$('take').classList.toggle('on',t==='포장')}
function renderCats(){$('catlist').innerHTML=Object.keys(S[store].cats).map(x=>`<button class="cat ${x===cat?'on':''}" onclick="chooseCat('${x}')">${x}</button>`).join('')}
function chooseCat(x){cat=x;renderCats();renderMenu()}
function renderMenu(){$('catTitle').textContent=cat;$('grid').innerHTML=S[store].cats[cat].map((x,i)=>`<button class="item" onclick="openItem('${cat}',${i})"><div class="pic"><img src="${x.img}" alt="${x.n}"></div><div class="itxt"><div class="iname">${x.n}</div><div class="price">${won(x.p)}${x.s?'~':''}</div></div></button>`).join('')}
function openItem(c,i){let x=S[store].cats[c][i],st={temp:x.t?'ICE':'없음',size:x.s?'보통':'없음'};openModal(`<div class="mh"><h3>${x.n}</h3><button class="x" onclick="closeModal()">×</button></div><div class="mb"><div class="detail"><img src="${x.img}" alt="${x.n}"></div>${x.t?`<div class="group"><b>온도를 선택하세요</b><div class="opts"><button class="opt sel" data-r="temp" data-v="ICE">ICE</button><button class="opt" data-r="temp" data-v="HOT">HOT</button></div></div>`:''}${x.s?`<div class="group"><b>크기를 선택하세요</b><div class="opts"><button class="opt sel" data-r="size" data-v="보통">보통</button><button class="opt" data-r="size" data-v="큰 사이즈">큰 사이즈 +500원</button></div></div>`:''}<button id="add" class="primary">장바구니에 담기</button></div>`,r=>{r.querySelectorAll('.opt').forEach(b=>b.onclick=()=>{st[b.dataset.r]=b.dataset.v;r.querySelectorAll(`[data-r="${b.dataset.r}"]`).forEach(q=>q.classList.remove('sel'));b.classList.add('sel')});r.querySelector('#add').onclick=()=>{addCart(x,st);closeModal()}})}
function addCart(x,s){let p=x.p+(s.size==='큰 사이즈'?500:0),key=[x.n,s.temp,s.size].join('|'),z=cart.find(v=>v.key===key);z?z.q++:cart.push({key,n:x.n,p,temp:s.temp,size:s.size,q:1});renderCart()}
function renderCart(){let t=cart.reduce((a,x)=>a+x.p*x.q,0);$('cartBox').innerHTML=cart.length?cart.map((x,i)=>`<div class="crow"><div class="cline"><span>${x.n}</span><span>${won(x.p*x.q)}</span></div><div class="copt">${[x.temp!=='없음'?x.temp:'',x.size!=='없음'?x.size:''].filter(Boolean).join(' · ')}</div><div class="qty"><button onclick="qty(${i},-1)">−</button><b>${x.q}</b><button onclick="qty(${i},1)">+</button></div></div>`).join(''):'<div class="empty">메뉴를 선택해 주세요.</div>';$('total').textContent=won(t);$('pay').disabled=!cart.length}
function qty(i,d){cart[i].q+=d;if(cart[i].q<=0)cart.splice(i,1);renderCart()}function total(){return cart.reduce((a,x)=>a+x.p*x.q,0)}function allItems(){return Object.values(S[store].cats).flat()}
function newMission(){let items=allItems(),r=Math.random(),pay=Math.random()<.5?'카드':'현금';if(r<.34){let x=items[Math.floor(Math.random()*items.length)];mission={type:'exact',items:[x.n],pay,ot:Math.random()<.5?'매장':'포장'};$('missionText').textContent=`${mission.ot}에서 ${x.n} 1개를 주문하고 ${pay}로 결제하세요.`}else if(r<.68){let a=items[Math.floor(Math.random()*items.length)],b=items[Math.floor(Math.random()*items.length)];while(b.n===a.n)b=items[Math.floor(Math.random()*items.length)];mission={type:'exact',items:[a.n,b.n],pay,ot:'포장'};$('missionText').textContent=`포장으로 ${a.n} 1개와 ${b.n} 1개를 주문하고 ${pay}로 결제하세요.`}else{mission={type:'budget',budget:10000,min:3,pay,ot:'매장'};$('missionText').textContent=`매장에서 10,000원 안으로 서로 다른 메뉴를 3개 이상 주문하고 ${pay}로 결제하세요.`}}
function speakMission(){if('speechSynthesis'in window){speechSynthesis.cancel();let u=new SpeechSynthesisUtterance($('missionText').textContent);u.lang='ko-KR';u.rate=.9;speechSynthesis.speak(u)}}
function openPayment(){openModal(`<div class="mh"><h3>결제 방법을 선택하세요</h3><button class="x" onclick="closeModal()">×</button></div><div class="mb"><div class="methods"><button id="card" class="method">카드 결제</button><button id="cashm" class="method">현금 결제</button></div><div class="summary"><b>결제할 금액</b><br><span style="font-size:1.4rem;font-weight:1000">${won(total())}</span></div></div>`,r=>{r.querySelector('#card').onclick=cardPay;r.querySelector('#cashm').onclick=cashPay})}
function cardPay(){openModal(`<div class="mh"><h3>카드 결제</h3><button class="x" onclick="closeModal()">×</button></div><div class="mb"><div style="height:180px;display:grid;place-items:center"><div style="width:210px;height:128px;border-radius:18px;background:linear-gradient(135deg,#254461,#5d7c96);transform:rotate(-7deg);box-shadow:0 16px 30px #0002;position:relative"><div style="width:34px;height:24px;border-radius:5px;background:#e5ce72;position:absolute;left:24px;top:44px"></div><b style="position:absolute;left:24px;bottom:18px;color:#fff;letter-spacing:2px">CARD</b></div></div><button class="primary" onclick="finishPay('카드',${total()})">카드 결제 완료</button></div>`)}
function cashPay(){money=0;openModal(`<div class="mh"><h3>현금 결제</h3><button class="x" onclick="closeModal()">×</button></div><div class="mb"><b>돈을 눌러 금액을 맞춰보세요.</b><div class="cash">${[100,500,1000,5000,10000,50000].map(v=>`<button onclick="addMoney(${v})">${won(v)}</button>`).join('')}</div><div class="summary"><div>상품 금액: <b>${won(total())}</b></div><div>낸 금액: <b id="paid">0원</b></div><div>거스름돈: <b id="change">0원</b></div></div><div class="actions"><button class="secondary" onclick="money=0;updMoney()">다시 내기</button><button class="primary" style="margin-top:0;flex:1" onclick="finishCash()">결제하기</button></div></div>`)}
function addMoney(v){money+=v;updMoney()}function updMoney(){$('paid').textContent=won(money);$('change').textContent=won(Math.max(0,money-total()))}function finishCash(){if(money<total())return alert('금액이 부족해요.');finishPay('현금',money)}
function missionOK(method){if(mode!=='mission'||!mission)return true;if(method!==mission.pay||orderType!==mission.ot)return false;let names=[];cart.forEach(x=>{for(let i=0;i<x.q;i++)names.push(x.n)});if(mission.type==='exact')return names.length===mission.items.length&&mission.items.every(n=>names.includes(n));return total()<=mission.budget&&new Set(names).size>=mission.min}
function finishPay(method,paid){let ok=missionOK(method),no=Math.floor(1000+Math.random()*9000);openModal(`<div class="mh"><h3>주문 완료</h3><button class="x" onclick="resetAfter()">×</button></div><div class="mb">${mode==='mission'?`<div class="result ${ok?'ok':'bad'}">${ok?'미션 성공! 정확하게 주문했어요.':'미션 조건과 달라요. 다시 도전해 보세요.'}</div>`:''}<div class="receipt"><h4>${S[store].title}</h4><p>${orderType} 주문</p><hr>${cart.map(x=>`<div class="rline"><span>${x.n} × ${x.q}</span><span>${won(x.p*x.q)}</span></div>`).join('')}<hr><div class="rline"><b>합계</b><b>${won(total())}</b></div><div class="rline"><span>결제</span><span>${method}</span></div>${method==='현금'?`<div class="rline"><span>받은 금액</span><span>${won(paid)}</span></div><div class="rline"><span>거스름돈</span><span>${won(paid-total())}</span></div>`:''}<hr><div class="order">${no}</div></div><button class="primary" style="margin-top:14px" onclick="resetAfter()">새 주문 시작</button></div>`)}
function resetAfter(){closeModal();cart=[];renderCart();if(mode==='mission')newMission()}function openModal(h,a){$('modal').innerHTML=`<div class="overlay"><div class="modal">${h}</div></div>`;if(a)a($('modal'))}function closeModal(){$('modal').innerHTML=''}home();