function home(){$('stores').innerHTML=Object.entries(S).map(([k,v])=>`<button class="storeCard" onclick="enter('${k}')"><div class="storeVisual">${art(v.hero==='cafe'?'latte':v.hero==='burger'?'cheeseburger':'tteok')}</div><div class="storeBody"><div class="storeName">${v.title}</div><div class="storeDesc">${v.desc}</div><span class="storeGo">주문하기</span></div></button>`).join('')}
function enter(k){store=k;cat=Object.keys(S[k].cats)[0];cart=[];document.body.className=k;$('home').classList.add('hidden');$('app').classList.remove('hidden');$('brand').textContent=S[k].title+' 키오스크';setMode('free');setOrderType('매장');renderCats();renderMenu();renderCart()}
function goHome(){$('app').classList.add('hidden');$('home').classList.remove('hidden');document.body.className='';closeModal()}
function setMode(m){mode=m;$('freeBtn').classList.toggle('on',m==='free');$('missionBtn').classList.toggle('on',m==='mission');$('missionBox').classList.toggle('hidden',m!=='mission');$('modeText').textContent=m==='free'?'자유롭게 주문해 보세요.':'미션을 보고 정확하게 주문해 보세요.';if(m==='mission')newMission()}
function setOrderType(t){orderType=t;$('dine').classList.toggle('on',t==='매장');$('take').classList.toggle('on',t==='포장')}
function renderCats(){$('catlist').innerHTML=Object.keys(S[store].cats).map(x=>`<button class="cat ${x===cat?'on':''}" onclick="chooseCat('${x}')">${x}</button>`).join('')}
function chooseCat(x){cat=x;renderCats();renderMenu()}
function renderMenu(){$('catTitle').textContent=cat;$('grid').innerHTML=S[store].cats[cat].map((x,i)=>`<button class="item" onclick="openItem('${cat}',${i})"><div class="pic">${art(x.a)}</div><div class="itxt"><div class="iname">${x.n}</div><div class="price">${won(x.p)}${x.s?'~':''}</div></div></button>`).join('')}
function openItem(c,i){let x=S[store].cats[c][i],st={temp:x.t?'ICE':'없음',size:x.s?'보통':'없음'};openModal(`<div class="mh"><h3>${x.n}</h3><button class="x" onclick="closeModal()">×</button></div><div class="mb"><div class="detail">${art(x.a)}</div>${x.t?`<div class="group"><b>온도를 선택하세요</b><div class="opts"><button class="opt sel" data-r="temp" data-v="ICE">ICE</button><button class="opt" data-r="temp" data-v="HOT">HOT</button></div></div>`:''}${x.s?`<div class="group"><b>크기를 선택하세요</b><div class="opts"><button class="opt sel" data-r="size" data-v="보통">보통</button><button class="opt" data-r="size" data-v="큰 사이즈">큰 사이즈 +500원</button></div></div>`:''}<button id="add" class="primary">장바구니에 담기</button></div>`,r=>{r.querySelectorAll('.opt').forEach(b=>b.onclick=()=>{st[b.dataset.r]=b.dataset.v;r.querySelectorAll(`[data-r="${b.dataset.r}"]`).forEach(q=>q.classList.remove('sel'));b.classList.add('sel')});r.querySelector('#add').onclick=()=>{addCart(x,st);closeModal()}})}
function addCart(x,s){let p=x.p+(s.size==='큰 사이즈'?500:0),key=[x.n,s.temp,s.size].join('|'),z=cart.find(v=>v.key===key);z?z.q++:cart.push({key,n:x.n,p,temp:s.temp,size:s.size,q:1});renderCart()}
function renderCart(){let t=cart.reduce((a,x)=>a+x.p*x.q,0);$('cartBox').innerHTML=cart.length?cart.map((x,i)=>`<div class="crow"><div class="cline"><span>${x.n}</span><span>${won(x.p*x.q)}</span></div><div class="copt">${[x.temp!=='없음'?x.temp:'',x.size!=='없음'?x.size:''].filter(Boolean).join(' · ')}</div><div class="qty"><button onclick="qty(${i},-1)">−</button><b>${x.q}</b><button onclick="qty(${i},1)">+</button></div></div>`).join(''):'<div class="empty">메뉴를 선택해 주세요.</div>';$('total').textContent=won(t);$('pay').disabled=!cart.length}
function qty(i,d){cart[i].q+=d;if(cart[i].q<=0)cart.splice(i,1);renderCart()}function total(){return cart.reduce((a,x)=>a+x.p*x.q,0)}function allItems(){return Object.values(S[store].cats).flat()}
function newMission(){let items=allItems(),r=Math.random(),pay=Math.random()<.5?'카드':'현금',ot=Math.random()<.5?'매장':'포장';if(r<.42){let x=items[Math.floor(Math.random()*items.length)],temp=x.t?(Math.random()<.5?'ICE':'HOT'):'없음',size=x.s?(Math.random()<.35?'큰 사이즈':'보통'):'없음';mission={type:'one',n:x.n,temp,size,pay,ot};$('missionText').textContent=`${ot}에서 ${temp!=='없음'?temp+' ':''}${size==='큰 사이즈'?'큰 사이즈 ':''}${x.n} 1개를 주문하고 ${pay}로 결제하세요.`}else if(r<.78){let a=items[Math.floor(Math.random()*items.length)],b=items[Math.floor(Math.random()*items.length)];while(b.n===a.n)b=items[Math.floor(Math.random()*items.length)];mission={type:'two',names:[a.n,b.n],pay,ot};$('missionText').textContent=`${ot}으로 ${a.n} 1개와 ${b.n} 1개를 주문하고 ${pay}로 결제하세요.`}else{mission={type:'budget',limit:12000,min:2,pay,ot};$('missionText').textContent=`${ot}에서 12,000원 안으로 서로 다른 메뉴를 2개 이상 주문하고 ${pay}로 결제하세요.`}}
function speakMission(){if('speechSynthesis'in window){speechSynthesis.cancel();let u=new SpeechSynthesisUtterance($('missionText').textContent);u.lang='ko-KR';u.rate=.9;speechSynthesis.speak(u)}}
function openPayment(){openModal(`<div class="mh"><h3>결제 방법을 선택하세요</h3><button class="x" onclick="closeModal()">×</button></div><div class="mb"><div class="methods"><button id="card" class="method">카드 결제</button><button id="cashm" class="method">현금 결제</button></div><div class="summary"><b>결제할 금액</b><br><span style="font-size:1.45rem;font-weight:1000">${won(total())}</span></div></div>`,r=>{r.querySelector('#card').onclick=cardPay;r.querySelector('#cashm').onclick=cashPay})}
function cardPay(){openModal(`<div class="mh"><h3>카드 결제</h3><button class="x" onclick="closeModal()">×</button></div><div class="mb"><div style="height:175px;display:grid;place-items:center"><div style="width:215px;height:130px;border-radius:18px;background:linear-gradient(135deg,#23435d,#5f7f98);transform:rotate(-7deg);box-shadow:0 14px 28px #0002;position:relative"><div style="width:34px;height:24px;border-radius:5px;background:#e4cb68;position:absolute;left:24px;top:44px"></div><b style="position:absolute;left:24px;bottom:18px;color:#fff;letter-spacing:2px">CARD</b></div></div><button class="primary" onclick="finishPay('카드',${total()})">카드 결제 완료</button></div>`)}
function cashPay(){money=0;openModal(`<div class="mh"><h3>현금 결제</h3><button class="x" onclick="closeModal()">×</button></div><div class="mb"><b>돈을 눌러 금액을 맞춰보세요.</b><div class="cash">${[100,500,1000,5000,10000,50000].map(v=>`<button onclick="addMoney(${v})">${won(v)}</button>`).join('')}</div><div class="summary"><div>상품 금액: <b>${won(total())}</b></div><div>낸 금액: <b id="paid">0원</b></div><div>거스름돈: <b id="change">0원</b></div></div><div class="actions"><button class="secondary" onclick="money=0;updMoney()">다시 내기</button><button class="primary" style="margin-top:0;flex:1" onclick="finishCash()">결제하기</button></div></div>`)}function addMoney(v){money+=v;updMoney()}function updMoney(){$('paid').textContent=won(money);$('change').textContent=won(Math.max(0,money-total()))}function finishCash(){if(money<total())return alert('금액이 부족해요.');finishPay('현금',money)}
function missionOK(method){if(mode!=='mission'||!mission)return true;if(method!==mission.pay||orderType!==mission.ot)return false;let rows=[];cart.forEach(x=>{for(let i=0;i<x.q;i++)rows.push(x)});if(mission.type==='one'){if(rows.length!==1)return false;let x=rows[0];return x.n===mission.n&&(mission.temp==='없음'||x.temp===mission.temp)&&(mission.size==='없음'||x.size===mission.size)}if(mission.type==='two'){let names=rows.map(x=>x.n);return names.length===2&&mission.names.every(n=>names.includes(n))}return total()<=mission.limit&&new Set(rows.map(x=>x.n)).size>=mission.min}
function finishPay(method,paid){let ok=missionOK(method),no=Math.floor(1000+Math.random()*9000);openModal(`<div class="mh"><h3>주문 완료</h3><button class="x" onclick="resetAfter()">×</button></div><div class="mb">${mode==='mission'?`<div class="result ${ok?'ok':'bad'}">${ok?'미션 성공! 정확하게 주문했어요.':'미션 조건과 달라요. 다시 도전해 보세요.'}</div>`:''}<div class="receipt"><h4>${S[store].title}</h4><p>${orderType} 주문</p><hr>${cart.map(x=>`<div class="rline"><span>${x.n} × ${x.q}</span><span>${won(x.p*x.q)}</span></div>`).join('')}<hr><div class="rline"><b>합계</b><b>${won(total())}</b></div><div class="rline"><span>결제</span><span>${method}</span></div>${method==='현금'?`<div class="rline"><span>받은 금액</span><span>${won(paid)}</span></div><div class="rline"><span>거스름돈</span><span>${won(paid-total())}</span></div>`:''}<hr><div class="orderNo">${no}</div></div><button class="primary" onclick="resetAfter()">새 주문 시작</button></div>`)}function resetAfter(){closeModal();cart=[];renderCart();if(mode==='mission')newMission()}function openModal(h,a){$('modal').innerHTML=`<div class="overlay"><div class="modal">${h}</div></div>`;if(a)a($('modal'))}function closeModal(){$('modal').innerHTML=''}home();